services:
#  rescheduler:
#    build:
#      context: .
#      dockerfile: src/Rescheduler.Api/Dockerfile
#    volumes:
#      - rescheduler-data:/app
#    environment:
#      LoggingFormat: "json"
#      Messaging__RabbitMq__Enabled: "true"
#      Messaging__RabbitMq__ConnectionString: "amqp://rabbitmq:rabbitmq@rabbitmq:5672/"
#      Messaging__ServiceBus__Enabled: "false"
#      Messaging__ServiceBus__PartitionedQueue: "false"
#      Messaging__ServiceBus__ConnectionString: ""
#      ASPNETCORE_ENVIRONMENT: Development
#    ports:
#      - "8080:80"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbit1"
    volumes:
      - ./docker/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672" # management port
      - "15692:15692" # metrics port
      - "5672:5672"
        
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1337:1337"   # pprof extension
      - "8080:8080"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver

volumes:
  rescheduler-data:
  rabbitmq-data:
