### Create job
POST http://localhost:5000/api/jobs HTTP/1.1
content-type: application/json

{
    "subject": "webhook",
    "payload": "test payload",
    "runAt": "2021-01-02T23:20:50.52Z",
    "stopAfter": "2022-01-02T23:20:50.52Z",
    "cron": "*/5 * * * *"
}

### Get executions
GET http://localhost:5000/api/jobs/executions?statuses=Scheduled&top=80
Accept: application/json

### Get jobs
GET http://localhost:5000/api/jobs?subject=webhook&top=20
Accept: application/json

### Get job
GET http://localhost:5000/api/jobs/620576f2-0817-4970-ad79-1c62f4267d0f
Accept: application/json

### Get job executions
GET http://localhost:5000/api/jobs/d1f0a03c-f31e-452c-829b-41a2547e6c08/executions
Accept: application/json