### Create job
POST http://localhost:8080/api/jobs HTTP/1.1
Content-Type: application/json

{
    "subject": "webhook",
    "payload": "test payload",
    "runAt": "2021-01-02T23:20:50.52Z",
    "stopAfter": "2022-01-02T23:20:50.52Z",
    "cron": "*/5 * * * *"
}

### Get executions
GET http://localhost:8080/api/jobs/executions?statuses=Scheduled&top=80
Accept: application/json

### Get jobs
GET http://localhost:8080/api/jobs?subject=webhook&top=20
Accept: application/json

### Get job
GET http://localhost:8080/api/jobs/59831da9-ef8d-418f-b04d-db03025ea2c1
Accept: application/json

### Get job executions
GET http://localhost:8080/api/jobs/59831da9-ef8d-418f-b04d-db03025ea2c1/executions
Accept: application/json