receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'

exporters:
  prometheus:
    endpoint: "0.0.0.0:8080"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: true
    resource_to_telemetry_conversion:
      enabled: false
  # Write telemetry to console 
  debug:
    
extensions:
  pprof:
    endpoint: '0.0.0.0:1337'
  health_check:
    endpoint: "0.0.0.0:13133"
    check_collector_pipeline:
      enabled: true

service:
  extensions: [pprof, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]