global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'loki:3100'
          - 'grafana:3000'
          - 'rabbitmq:15692'
          - 'rescheduler:80'
