name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings .github/coverlet.xml
  
  coverage:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --settings .github/coverlet.xml

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/coverage.opencover.xml"
          verbose: true

  sonar:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore tools
      run: dotnet tool restore
        
    - name: Begin collect
      run: dotnet sonarscanner begin /k:"mkromkamp_rescheduler-lite" /o:"mkromkamp" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        
    - name: Test
      run: |
        dotnet build --no-incremental
        dotnet coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
        
    - name: End collect
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

