name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore Rescheduler.sln

    - name: Build
      run: dotnet build Rescheduler.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Rescheduler.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    # - name: Copy Coverage To Predictable Location
    #   run: cp -n coverage/**/coverage.cobertura.xml coverage.cobertura.xml

    - name: Collect coverage files
      id: coverage
      run: find ./coverage | grep coverage.cobertura.xml | xargs | tr ' ' ','
      env: 
        coverage_files: find ./coverage | grep coverage.cobertura.xml | xargs | tr ' ' ','

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: ${{ env.COVERAGE_FILES }} #coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
